datasource:
  default:
    providerClass: org.hibernate.jpa.HibernatePersistenceProvider
    jdbcDriver: org.h2.Driver
    jdbcUrl: jdbc:h2:./example/example
    user:
    password:
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
flyway:
  default:
    location: flyway
authenticationProvider:
  jsonFileName: credentials.json
  openIdDiscoveryUri: https://accounts.google.com/.well-known/openid-configuration
  callbackPath: /login