datasource:
  default:
    providerClass: org.hibernate.jpa.HibernatePersistenceProvider
    jdbcDriver: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://localhost:5432/nnsfw
    user: postgres
    password: postgres
    connection:
      max: 50
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
flyway:
  default:
    location: flyway
authenticationProvider:
  jsonFileName: credentials.json
  openIdDiscoveryUri: https://accounts.google.com/.well-known/openid-configuration
  callbackPath: /login